// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/vesting/dchainv1/abstract_vesting.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NilPubKey is the pubkey type of the AbstractAccount. Basically, it represents
// a pubkey that doesn't exist.
//
// The actual pubkey of an AbstractAccount (if it has one) is to be stored
// inside the contract, not at the SDK level. Signature verification is also
// done inside the contract, typically in the BeforeTx hook.
type NilPubKey struct {
	AddressBytes []byte `protobuf:"bytes,1,opt,name=address_bytes,json=addressBytes,proto3" json:"address_bytes,omitempty"`
}

func (m *NilPubKey) Reset()      { *m = NilPubKey{} }
func (*NilPubKey) ProtoMessage() {}
func (*NilPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fbf5ff87672325, []int{0}
}
func (m *NilPubKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NilPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NilPubKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NilPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NilPubKey.Merge(m, src)
}
func (m *NilPubKey) XXX_Size() int {
	return m.Size()
}
func (m *NilPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NilPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_NilPubKey proto.InternalMessageInfo

func (m *NilPubKey) GetAddressBytes() []byte {
	if m != nil {
		return m.AddressBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*NilPubKey)(nil), "cosmos.vesting.dchainv1.NilPubKey")
}

func init() {
	proto.RegisterFile("cosmos/vesting/dchainv1/abstract_vesting.proto", fileDescriptor_04fbf5ff87672325)
}

var fileDescriptor_04fbf5ff87672325 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x2f, 0x4b, 0x2d, 0x2e, 0xc9, 0xcc, 0x4b, 0xd7, 0x4f, 0x49, 0xce, 0x48, 0xcc,
	0xcc, 0x2b, 0x33, 0xd4, 0x4f, 0x4c, 0x2a, 0x2e, 0x29, 0x4a, 0x4c, 0x2e, 0x89, 0x87, 0xca, 0xe8,
	0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x89, 0x43, 0xd4, 0xeb, 0xc1, 0x44, 0x61, 0xea, 0xa5, 0x44,
	0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0x6a, 0xf4, 0x41, 0x2c, 0x88, 0x72, 0x25, 0x33, 0x2e, 0x4e, 0xbf,
	0xcc, 0x9c, 0x80, 0xd2, 0x24, 0xef, 0xd4, 0x4a, 0x21, 0x65, 0x2e, 0xde, 0xc4, 0x94, 0x94, 0xa2,
	0xd4, 0xe2, 0xe2, 0xf8, 0xa4, 0xca, 0x92, 0xd4, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x1e, 0xa8, 0xa0, 0x13, 0x48, 0xcc, 0x8a, 0x65, 0xc6, 0x02, 0x79, 0x06, 0x27, 0xef, 0x13, 0x8f,
	0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b,
	0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0x32, 0x4c, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2,
	0x4b, 0xce, 0xcf, 0xd5, 0x87, 0xba, 0x1d, 0x42, 0xe9, 0x16, 0xa7, 0x64, 0xeb, 0x57, 0xe8, 0x27,
	0x96, 0x96, 0x64, 0xc0, 0x7d, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x76, 0x8b, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xfa, 0xdd, 0x6e, 0xec, 0x00, 0x00, 0x00,
}

func (m *NilPubKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NilPubKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NilPubKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AddressBytes) > 0 {
		i -= len(m.AddressBytes)
		copy(dAtA[i:], m.AddressBytes)
		i = encodeVarintAbstractVesting(dAtA, i, uint64(len(m.AddressBytes)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAbstractVesting(dAtA []byte, offset int, v uint64) int {
	offset -= sovAbstractVesting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NilPubKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AddressBytes)
	if l > 0 {
		n += 1 + l + sovAbstractVesting(uint64(l))
	}
	return n
}

func sovAbstractVesting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAbstractVesting(x uint64) (n int) {
	return sovAbstractVesting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NilPubKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAbstractVesting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NilPubKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NilPubKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAbstractVesting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAbstractVesting
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAbstractVesting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressBytes = append(m.AddressBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.AddressBytes == nil {
				m.AddressBytes = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAbstractVesting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAbstractVesting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAbstractVesting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAbstractVesting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAbstractVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAbstractVesting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAbstractVesting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAbstractVesting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAbstractVesting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAbstractVesting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAbstractVesting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAbstractVesting = fmt.Errorf("proto: unexpected end of group")
)
