// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol/chain/sdjwt/v0/types.proto

package tx

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8667db34f2b06b02, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// The sdjwt verifier contract type to be stored in the module
// FIXME: proto attributes?
type SdJwtVerifierContract struct {
	CodeId          uint64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CodeHash        []byte `protobuf:"bytes,2,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	ContractAddress string `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
}

func (m *SdJwtVerifierContract) Reset()         { *m = SdJwtVerifierContract{} }
func (m *SdJwtVerifierContract) String() string { return proto.CompactTextString(m) }
func (*SdJwtVerifierContract) ProtoMessage()    {}
func (*SdJwtVerifierContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8667db34f2b06b02, []int{2}
}
func (m *SdJwtVerifierContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SdJwtVerifierContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SdJwtVerifierContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SdJwtVerifierContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SdJwtVerifierContract.Merge(m, src)
}
func (m *SdJwtVerifierContract) XXX_Size() int {
	return m.Size()
}
func (m *SdJwtVerifierContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SdJwtVerifierContract.DiscardUnknown(m)
}

var xxx_messageInfo_SdJwtVerifierContract proto.InternalMessageInfo

func (m *SdJwtVerifierContract) GetCodeId() uint64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *SdJwtVerifierContract) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *SdJwtVerifierContract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type VerifiablePresentation struct {
	Presentation []byte `protobuf:"bytes,1,opt,name=presentation,proto3" json:"presentation,omitempty"`
}

func (m *VerifiablePresentation) Reset()         { *m = VerifiablePresentation{} }
func (m *VerifiablePresentation) String() string { return proto.CompactTextString(m) }
func (*VerifiablePresentation) ProtoMessage()    {}
func (*VerifiablePresentation) Descriptor() ([]byte, []int) {
	return fileDescriptor_8667db34f2b06b02, []int{3}
}
func (m *VerifiablePresentation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifiablePresentation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifiablePresentation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifiablePresentation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiablePresentation.Merge(m, src)
}
func (m *VerifiablePresentation) XXX_Size() int {
	return m.Size()
}
func (m *VerifiablePresentation) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiablePresentation.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiablePresentation proto.InternalMessageInfo

func (m *VerifiablePresentation) GetPresentation() []byte {
	if m != nil {
		return m.Presentation
	}
	return nil
}

var fileDescriptor_8667db34f2b06b02 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x6e, 0xda, 0x30,
	0x1c, 0x8e, 0x37, 0x94, 0x81, 0x17, 0x69, 0x2c, 0x62, 0x23, 0x63, 0x52, 0x40, 0xd9, 0x85, 0x0b,
	0x0e, 0xda, 0xae, 0xdb, 0x61, 0x70, 0xd8, 0xca, 0x09, 0x05, 0xa9, 0x87, 0xf6, 0x10, 0x99, 0xd8,
	0x10, 0x57, 0x10, 0x47, 0xb6, 0x15, 0xda, 0xb7, 0xa8, 0xfa, 0x18, 0x3d, 0xf7, 0x21, 0x38, 0xa2,
	0x9e, 0x7a, 0xaa, 0x2a, 0x78, 0x91, 0x2a, 0x4e, 0x90, 0x5a, 0x54, 0x6e, 0xfe, 0x7d, 0x7f, 0x7e,
	0xfe, 0x64, 0x7f, 0xf0, 0x47, 0x2a, 0xb8, 0xe2, 0x11, 0x5f, 0xf8, 0x51, 0x8c, 0x59, 0xe2, 0x4b,
	0x72, 0xb1, 0x52, 0x7e, 0xd6, 0xf7, 0xd5, 0x55, 0x4a, 0x25, 0xd2, 0xac, 0xdd, 0xdc, 0x8b, 0x90,
	0x16, 0x21, 0x2d, 0x42, 0x59, 0xbf, 0xf5, 0x2d, 0xe2, 0x72, 0xc9, 0x65, 0xa8, 0x79, 0xbf, 0x18,
	0x0a, 0x4f, 0xab, 0x31, 0xe7, 0x73, 0x5e, 0xe0, 0xf9, 0xa9, 0x40, 0xbd, 0x2a, 0x34, 0xc7, 0x58,
	0xe0, 0xa5, 0xf4, 0x6e, 0x01, 0xb4, 0xfe, 0xd1, 0x84, 0x4a, 0x26, 0x27, 0x0a, 0x2b, 0x6a, 0xff,
	0x81, 0x66, 0xaa, 0x29, 0x07, 0x74, 0x40, 0xf7, 0xe3, 0xcf, 0x36, 0x3a, 0x72, 0x2b, 0x2a, 0x36,
	0x0c, 0x2a, 0xeb, 0xc7, 0xb6, 0x11, 0x94, 0x26, 0xfb, 0x1c, 0x7e, 0xce, 0xa8, 0x60, 0x33, 0x46,
	0x45, 0x18, 0xf1, 0x44, 0x09, 0x1c, 0x29, 0xe7, 0x9d, 0xde, 0x84, 0x8e, 0x6e, 0x9a, 0x90, 0xd1,
	0x4a, 0x9d, 0x96, 0xb6, 0x61, 0xe9, 0x0a, 0xea, 0xd9, 0x01, 0xe2, 0xdd, 0x00, 0xf8, 0xe5, 0x4d,
	0xad, 0xdd, 0x84, 0x1f, 0x22, 0x4e, 0x68, 0xc8, 0x88, 0x8e, 0x5d, 0x09, 0xcc, 0x7c, 0x3c, 0x21,
	0xf6, 0x77, 0x58, 0xd3, 0x44, 0x8c, 0x65, 0xac, 0x73, 0x58, 0x41, 0x35, 0x07, 0xfe, 0x63, 0x19,
	0xdb, 0x43, 0x58, 0xdf, 0x67, 0x0c, 0x31, 0x21, 0x82, 0x4a, 0xe9, 0xbc, 0xef, 0x80, 0x6e, 0x6d,
	0xe0, 0xdc, 0xdf, 0xf5, 0x1a, 0xe5, 0x43, 0xfe, 0x2d, 0x98, 0x89, 0x12, 0x2c, 0x99, 0x07, 0x9f,
	0xf6, 0x8e, 0x12, 0xf6, 0x7e, 0xc3, 0xaf, 0x45, 0x1c, 0x3c, 0x5d, 0xd0, 0xb1, 0xa0, 0x92, 0x26,
	0x0a, 0x2b, 0xc6, 0x13, 0xdb, 0x83, 0x56, 0xfa, 0x62, 0xd6, 0xc9, 0xac, 0xe0, 0x15, 0x36, 0x18,
	0xad, 0xb7, 0x2e, 0xd8, 0x6c, 0x5d, 0xf0, 0xb4, 0x75, 0xc1, 0xf5, 0xce, 0x35, 0x36, 0x3b, 0xd7,
	0x78, 0xd8, 0xb9, 0xc6, 0x59, 0x5f, 0xd0, 0x34, 0xff, 0xc6, 0x05, 0x56, 0x33, 0x2e, 0x96, 0x3d,
	0x82, 0x18, 0xf7, 0x0f, 0x6a, 0x72, 0x59, 0x16, 0x45, 0xb7, 0x64, 0x6a, 0x6a, 0xf6, 0xd7, 0x73,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x72, 0xb3, 0x4b, 0x4d, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *SdJwtVerifierContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SdJwtVerifierContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SdJwtVerifierContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CodeHash) > 0 {
		i -= len(m.CodeHash)
		copy(dAtA[i:], m.CodeHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CodeHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.CodeId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CodeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VerifiablePresentation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifiablePresentation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifiablePresentation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Presentation) > 0 {
		i -= len(m.Presentation)
		copy(dAtA[i:], m.Presentation)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Presentation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *SdJwtVerifierContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CodeId != 0 {
		n += 1 + sovTypes(uint64(m.CodeId))
	}
	l = len(m.CodeHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VerifiablePresentation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Presentation)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SdJwtVerifierContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SdJwtVerifierContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SdJwtVerifierContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeId", wireType)
			}
			m.CodeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CodeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CodeHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CodeHash = append(m.CodeHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CodeHash == nil {
				m.CodeHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifiablePresentation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifiablePresentation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifiablePresentation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Presentation", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Presentation = append(m.Presentation[:0], dAtA[iNdEx:postIndex]...)
			if m.Presentation == nil {
				m.Presentation = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
